services:
  burnincontrol.stationservice:
    image: aelmendorf234/station-service:latest
    container_name: station_service
    pull_policy: always
    privileged: true
    restart: unless-stopped
    user: "root"
    entrypoint: ["ash", "-c", "/scripts/entry-point.sh"]
    ports:
      - "5000:5000"
    volumes:
      - /home/setiburnin/StationSoft/StationService/app:/scripts
      - /dev:/dev
