version : '3.8'
services:
  mongodb:
    image: mongodb-raspberrypi4-unofficial-r7.0.4
    container_name: mongodb
    pull_policy: never
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - /home/setitech/StationSoft/mongo/db:/data/db
    labels:
      - "com.centurylinklabs.watchtower.enable=false"